# must be unique in a given instance
sonar.projectKey=alx-home_promise_4d0d1d2f-bd15-4ba9-8b0e-1b25f4b783ce

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0
 
# Analyze only library sources, not generated build artifacts.
sonar.sources=include,src
sonar.tests=test
sonar.inclusions=include/**,src/**
sonar.exclusions=build/**,.venv/**,_deps/**
sonar.coverage.exclusions=test/**,conanfile.py,src/Memcheck.cpp
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# mandatory: files to be handled by the _cxx plugin_
sonar.cxx.file.suffixes=.h,.cpp,.inl,.hpp,.hh,.cxx,.hxx
sonar.coverageReportPaths=coverage/sonar-coverage.xml
sonar.clientcert.path=/tmp/certs.p12
sonar.clientcert.password=${env.SONAR_CERT_PWD}
sonar.scanner.keystorePath=/tmp/certs.p12
sonar.scanner.keystorePassword=${env.SONAR_CERT_PWD}

sonar.cfamily.threads=32
sonar.cfamily.cache.enabled=true
sonar.cfamily.cache.path=.sonar_cache
